### ISSUE TITLE
Error running the model

### ISSUE THREAD

**Issue by Maiyourathaan** [BjornNyberg/Geometric-Attributes-Toolbox#11]
Hi Bjorn,
I am having problem when i run your tool, what ever function i run, it is giving me the following error.

No module named 'networkx'

Error loading modules - please install the necessary python module

![image](https://user-images.githubusercontent.com/88880005/179750672-a3662dcc-8486-4585-bb3c-cc43b38f8ad8.png)

**Comment by BjornNyberg** [comment]
Hi @Maiyourathaan 

Did you install NetworkGT using the installation [guide?](https://github.com/BjornNyberg/NetworkGT/wiki/Installation)

If you have already installed NetworkGT, we need to do some troubleshooting.

Cheers,
Björn

**Comment by BjornNyberg** [comment]
Hi @Maiyourathaan 

What operating system do you have? If you have Mac OSX you will need to install the 'networkx' module manually (See [here](https://gis.stackexchange.com/questions/351280/installing-python-modules-for-qgis-3-on-mac) for getting started). Otherwise 'networkx' should be available in QGIS as standard for the Windows OS.

If you only need the 'Remove Overlap' tool, I have removed this module from the script (simply reinstall the plugin) as it was not needed. However, if you need some of the other tools, e.g., centerlines or centerline orientations, you will need that NetworkX module.

Let me know if this helps. 

Cheers,
Björn
