### ISSUE TITLE
Utilizing own centreline for polygon width calculation

### ISSUE THREAD

**Issue by ghost** [BjornNyberg/Geometric-Attributes-Toolbox#14]
Hi,

Thanks for developing this tool!

Question - Can I use own centreline to generate width?

Use case:
Utilize own centreline to generate width calculations for waterbody polygons. Centre lines through waterbodies has already been generated by national provider. Obtaining width measurements at set intervals is goal.

Background:
- Have read through documentation. Do not see mention that using own centreline is invalid.
- Have run `centreline` generation and determined that `ID` field links centreline and waterbody.
- Test set generated made up of one polygon and centreline (multiline to single). Added field `ID = 0` in each.

![image](https://user-images.githubusercontent.com/60985476/211612052-9b6828fe-ffea-4dfc-bbfa-18206e9c68c8.png)

No features are written.
![image](https://user-images.githubusercontent.com/60985476/211612089-b1494b5c-616f-4ee8-a43e-ef310c978d03.png)

Environment:
- Windows 10
- QGIS 3.28.2
- Geometric Attributes Toolbox installed from Plugin Manager.

Thanks so much for any help:)

Richard

**Comment by BjornNyberg** [comment]
Hi Richard,

Thanks for this comment. Unfortunately this is a part that is not well documented in the wiki. There are two options to create width measurements from your own centerline:

The first option is the easiest to run by utilizing the 'Transects by Distance' tool that will create a perpendicular width measurement along the centerline at each specified distance point and does not require an ID field. However, this option will not cut the width measurement to the polygon shape.

![Presentation1](https://user-images.githubusercontent.com/37108459/211663551-138d6c1c-944e-497a-89b6-5425db269a04.gif)

Option two is somewhat more cumbersome and prone to erros but requires the following steps:

1. As you mentioned both the centerline and polygon **need a unique 'ID' field that is case sensitive!**
2. Run the 'Distance Along Centerline' tool found under the Line Tools tab to create a new 'Distance' field required by the algorithm. **Note** - Use the explode lines function otherwise there will be only one distance measurement. If you require multiple distance segments then apply the 'Vertex Density' option as well.
3. Run the 'Geometric Attributes' tool found under the Polygon Tools tab to create the width measurements.

![Presentation2](https://user-images.githubusercontent.com/37108459/211665198-9bbcd552-61eb-4bde-9a88-b516a501a75e.gif)

Hopefully that helps @richardburcher 
Björn

**Comment by ghost** [comment]
Thanks so much Björn for this.

Was able to replicate with Transects by Distance.

This approach will help with our project work☺

Cheers,

Richard

Richard Burcher (he/him, il/lui)

Software Specialist
Ocean, Coastal and River Engineering National Research Council
National Research Council Canada / Government of Canada

Developpeur Logiciels
Génie Océanique, Côtier et Fluvial
Conseil national de recherches Canada / Gouvernement du Canada

**Comment by ghost** [comment]
Closing issue as it has been resolved.

Thanks again for the help!!
