### ISSUE TITLE
Plug don't generate layer in output

### ISSUE THREAD

**Issue by bellanz80** [BjornNyberg/Geometric-Attributes-Toolbox#3]
Hi, I installed the plug. At the beginning I get a window that is locked. I installed the Networkx plug separately but nothing changed.
![66](https://user-images.githubusercontent.com/38449926/64440199-2d476600-d091-11e9-8887-ae5d55b7d51e.jpg)

Successively, I restarted the computer, and the plug seems to boot, but when using the congo test data, the layers that are generated are empty
![67](https://user-images.githubusercontent.com/38449926/64440211-31738380-d091-11e9-9d65-e46f12952edb.jpg)
Thank's for your help!
Luca

**Comment by BjornNyberg** [comment]
Hi Luca,

Networkx should be installed by default for QGIS 3.x. However, some important requirement is that you have installed SAGA GIS, the output is saved as a .shp file and the Congo River dataset is in the World Equal Area Cylindrical projection. This should now be explicitly stated in a later updated version. Have you attempted to reinstall the plugin? 

Otherwise there might be errors that are not reported. Try locating your plugin folder https://gis.stackexchange.com/questions/274311/qgis-3-plugin-folder-location
and edit the Centerlines.py file - change lines 251 and 252 to read...

```
#continue
feedback.reportError(QCoreApplication.translate('Error','%s'%(e)))
```

Do you see any changes?

**Comment by BjornNyberg** [comment]
I have received feedback from others and the issue appears to stem from saving the file in memory. This is because the centerline algorithm uses SAGA GIS to generate voronoi lines which requires a specific file location.

Temporary fix - save the file as a .shp

Feel free the reopen the issue if the problem persists.
